## This file should be loaded under <robot description>_planning

## the definition of each group
groups:

  - name: robot_body
    joints:
      torso_lift_joint
    links:
      base_link
      torso_lift_link
      head_pan_link
      head_tilt_link
      laser_tilt_mount_link
      base_laser_link
      base_bellow_link
      bl_caster_l_wheel_link
      bl_caster_r_wheel_link
      br_caster_l_wheel_link
      br_caster_r_wheel_link
      fl_caster_l_wheel_link
      fl_caster_r_wheel_link
      fr_caster_l_wheel_link
      fr_caster_r_wheel_link
      fr_caster_rotation_link
      br_caster_rotation_link
      bl_caster_rotation_link
      fl_caster_rotation_link

  - name: left_arm
    joints:
      l_shoulder_pan_joint
      l_shoulder_lift_joint
      l_upper_arm_roll_joint
      l_elbow_flex_joint
      l_forearm_roll_joint
      l_wrist_flex_joint
      l_wrist_roll_joint
    links:
      l_shoulder_pan_link
      l_shoulder_lift_link
      l_upper_arm_link
      l_upper_arm_roll_link
      l_elbow_flex_link
      l_forearm_link
      l_forearm_roll_link
      l_forearm_cam_frame
      l_wrist_flex_link
      l_wrist_roll_link

  - name: right_arm
    joints:
      r_shoulder_pan_joint
      r_shoulder_lift_joint
      r_upper_arm_roll_joint
      r_elbow_flex_joint
      r_forearm_roll_joint
      r_wrist_flex_joint
      r_wrist_roll_joint
    links: 
      r_shoulder_pan_link
      r_shoulder_lift_link
      r_upper_arm_link
      r_upper_arm_roll_link
      r_elbow_flex_link
      r_forearm_link
      r_forearm_roll_link
      r_wrist_flex_link
      r_wrist_roll_link
      r_gripper_palm_link
      r_gripper_l_finger_link
      r_gripper_r_finger_link
      r_gripper_l_finger_tip_link
      r_gripper_r_finger_tip_link
      r_gripper_motor_accelerometer_link

  - name: right_arm_and_end_effector
    joints:
      r_shoulder_pan_joint
      r_shoulder_lift_joint
      r_upper_arm_roll_joint
      r_elbow_flex_joint
      r_forearm_roll_joint
      r_wrist_flex_joint
      r_wrist_roll_joint
    links: 
      r_shoulder_pan_link
      r_shoulder_lift_link
      r_upper_arm_link
      r_upper_arm_roll_link
      r_elbow_flex_link
      r_forearm_link
      r_forearm_roll_link
      r_wrist_flex_link
      r_wrist_roll_link
      r_gripper_palm_link
      r_gripper_l_finger_link
      r_gripper_r_finger_link
      r_gripper_l_finger_tip_link
      r_gripper_r_finger_tip_link
      r_gripper_l_finger_tip_frame
      r_gripper_motor_accelerometer_link

  - name: left_arm_and_end_effector
    joints:
      l_shoulder_pan_joint
      l_shoulder_lift_joint
      l_upper_arm_roll_joint
      l_elbow_flex_joint
      l_forearm_roll_joint
      l_wrist_flex_joint
      l_wrist_roll_joint
    links: 
      l_shoulder_pan_link
      l_shoulder_lift_link
      l_upper_arm_link
      l_upper_arm_roll_link
      l_elbow_flex_link
      l_forearm_link
      l_forearm_roll_link
      l_forearm_cam_frame
      l_wrist_flex_link
      l_wrist_roll_link
      l_gripper_palm_link
      l_gripper_l_finger_link
      l_gripper_r_finger_link
      l_gripper_l_finger_tip_link
      l_gripper_r_finger_tip_link
      l_forearm_cam_optical_frame
      l_gripper_l_finger_tip_frame
      l_gripper_led_frame
      l_gripper_motor_accelerometer_link
      l_gripper_tool_frame
      
  - name: arms
    joints: 
      l_shoulder_pan_joint
      l_shoulder_lift_joint
      l_upper_arm_roll_joint
      l_elbow_flex_joint
      l_forearm_roll_joint
      l_wrist_flex_joint
      l_wrist_roll_joint
      r_shoulder_pan_joint
      r_shoulder_lift_joint
      r_upper_arm_roll_joint
      r_elbow_flex_joint
      r_forearm_roll_joint
      r_wrist_flex_joint
      r_wrist_roll_joint
    links:
      l_shoulder_pan_link
      l_shoulder_lift_link
      l_upper_arm_link
      l_upper_arm_roll_link
      l_forearm_link
      l_forearm_roll_link
      l_forearm_cam_frame
      l_wrist_flex_link
      l_wrist_roll_link
      r_shoulder_pan_link
      r_shoulder_lift_link
      r_upper_arm_link
      r_upper_arm_roll_link
      r_forearm_link
      r_forearm_roll_link
      r_forearm_cam_frame
      r_wrist_flex_link
      r_wrist_roll_link

  - name: l_end_effector
    links: 
      l_gripper_palm_link
      l_gripper_l_finger_link
      l_gripper_r_finger_link
      l_gripper_l_finger_tip_link
      l_gripper_r_finger_tip_link

  - name: r_end_effector
    links: 
      r_gripper_palm_link
      r_gripper_l_finger_link
      r_gripper_r_finger_link
      r_gripper_l_finger_tip_link
      r_gripper_r_finger_tip_link

  - name: arms_and_end_effectors
    joints:
      r_shoulder_pan_joint
      r_shoulder_lift_joint
      r_upper_arm_roll_joint
      r_elbow_flex_joint
      r_forearm_roll_joint
      r_wrist_flex_joint
      r_wrist_roll_joint
      l_shoulder_pan_joint
      l_shoulder_lift_joint
      l_upper_arm_roll_joint
      l_elbow_flex_joint
      l_forearm_roll_joint
      l_wrist_flex_joint
      l_wrist_roll_joint
    links:
      r_shoulder_pan_link
      r_shoulder_lift_link
      r_upper_arm_link
      r_upper_arm_roll_link
      r_elbow_flex_link
      r_forearm_link
      r_forearm_roll_link
      r_forearm_cam_frame
      r_wrist_flex_link
      r_wrist_roll_link
      r_gripper_palm_link
      r_gripper_l_finger_link
      r_gripper_r_finger_link
      r_gripper_l_finger_tip_link
      r_gripper_r_finger_tip_link
      r_forearm_cam_optical_frame
      r_gripper_l_finger_tip_frame
      r_gripper_led_frame
      r_gripper_motor_accelerometer_link
      r_gripper_tool_frame
      l_shoulder_pan_link
      l_shoulder_lift_link
      l_upper_arm_link
      l_upper_arm_roll_link
      l_elbow_flex_link
      l_forearm_link
      l_forearm_roll_link
      l_forearm_cam_frame
      l_wrist_flex_link
      l_wrist_roll_link
      l_gripper_palm_link
      l_gripper_l_finger_link
      l_gripper_r_finger_link
      l_gripper_l_finger_tip_link
      l_gripper_r_finger_tip_link
      l_forearm_cam_optical_frame
      l_gripper_l_finger_tip_frame
      l_gripper_led_frame
      l_gripper_motor_accelerometer_link
      l_gripper_tool_frame